using System;
using System.Collections.Generic;
using System.Text;

/* Problem 12 - Highly Divisible Triangular Number
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 +
4 + 5 + 6 + 7 = 28. The first ten terms would be:
                        1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
 */

namespace ProjectEuler.Problems
{
    class ID12
    {
        public void Start()
        {
            Console.WriteLine("Problem 12 - Highly Divisible Triangular Number\n" +
                "The sequence of triangle numbers is generated by adding the natural numbers.\n" +
                "What is the value of the first triangle number to have over five hundred divisors?\n" +
                "Press any key to start...\n");
            Console.ReadKey();

            int natural = 1;
            int triangle = 0;
            int maxDivisors = 0;
            while(triangle < int.MaxValue)
            {
                triangle += natural;
                natural++;
                int divisors = 1;
                for(int divisor = triangle/2; divisor > 0; divisor--)
                {
                    if(triangle % divisor == 0) { divisors++; }
                    if (triangle % 2 != 0 & divisor != 1)
                    {
                        divisor--;
                    }
                }
                if (divisors > maxDivisors)
                { Console.WriteLine($"{triangle}: {divisors} divisors"); maxDivisors = divisors; }
                if (divisors > 500) { Console.WriteLine($"\n{triangle}: {divisors} divisors"); return; }
            }
        }
    }
}
