using System;
using System.Collections.Generic;
using System.Text;
/* Problem 2 - Even Fibonacci Numbers
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
namespace ProjectEuler.Problems
{
    class ID2
    {
        public void Start()
        {
            Console.WriteLine("Problem 2 - Even Fibonacci Numbers:\n" +
                "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n" +
                "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n" +
                "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.\n");
            Console.WriteLine("Press any key to start...\n");
            Console.ReadKey();
            Console.WriteLine($"\nResult:{EvenFibonacci()}\n");
            
        }

        private int EvenFibonacci()
        {
            int result = 0, fib = 1, previousFib = 1, previousFib2 = 0;
            while(fib < 4000000)
            {
                if (fib%2 == 0)
                { result += fib; }
                previousFib2 = previousFib;
                previousFib = fib;
                fib = previousFib + previousFib2;
            }

            return result;
        }
    }
}
